# Generated by Django 3.2.5 on 2022-03-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste_taches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liste',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
